# .github/workflows/run-colab.yml
name: Run Colab Daily

on:
  schedule:
    - cron: "30 10 * * *" # 10:30 UTC = 2:30 AM PST
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Notebook
        uses: agyemanjp/run-colab-notebook@v1.2
        with:
          notebook-path: "YOUR_NOTEBOOK.ipynb"
